### ISSUE TITLE
node chatter crashes

### ISSUE THREAD

**Issue by jquast** [jquast/x84#149]
```
Sat-12-27 08:43PM INFO  session.py:500 hamster[telnet-92.32.84.20:63784] page from -1.
Sat-12-27 08:43PM ERROR  session.py:396 hamster[telnet-92.32.84.20:63784]   File "x84/bbs/session.py", line 370, in run
Sat-12-27 08:43PM ERROR  session.py:396 hamster[telnet-92.32.84.20:63784]     self.runscript(self._script_stack.pop())
Sat-12-27 08:43PM ERROR  session.py:396 hamster[telnet-92.32.84.20:63784] 
Sat-12-27 08:43PM ERROR  session.py:396 hamster[telnet-92.32.84.20:63784]   File "x84/bbs/session.py", line 662, in runscript
Sat-12-27 08:43PM ERROR  session.py:396 hamster[telnet-92.32.84.20:63784]     value = module.main(*script.args, **script.kwargs)
Sat-12-27 08:43PM ERROR  session.py:396 hamster[telnet-92.32.84.20:63784] 
Sat-12-27 08:43PM ERROR  session.py:396 hamster[telnet-92.32.84.20:63784]   File "/home/bld/.x84/bbs/main.py", line 114, in main
Sat-12-27 08:43PM ERROR  session.py:396 hamster[telnet-92.32.84.20:63784]     inp = le.read()
Sat-12-27 08:43PM ERROR  session.py:396 hamster[telnet-92.32.84.20:63784] 
Sat-12-27 08:43PM ERROR  session.py:396 hamster[telnet-92.32.84.20:63784]   File "x84/bbs/editor.py", line 185, in read
Sat-12-27 08:43PM ERROR  session.py:396 hamster[telnet-92.32.84.20:63784]     inp = getch()
Sat-12-27 08:43PM ERROR  session.py:396 hamster[telnet-92.32.84.20:63784] 
Sat-12-27 08:43PM ERROR  session.py:396 hamster[telnet-92.32.84.20:63784]   File "x84/bbs/__init__.py", line 115, in getch
Sat-12-27 08:43PM ERROR  session.py:396 hamster[telnet-92.32.84.20:63784]     keystroke = getterminal().inkey(timeout)
Sat-12-27 08:43PM ERROR  session.py:396 hamster[telnet-92.32.84.20:63784] 
Sat-12-27 08:43PM ERROR  session.py:396 hamster[telnet-92.32.84.20:63784]   File "x84/terminal.py", line 31, in inkey
Sat-12-27 08:43PM ERROR  session.py:396 hamster[telnet-92.32.84.20:63784]     return BlessedTerminal.inkey(self, timeout, esc_delay=0.35)
Sat-12-27 08:43PM ERROR  session.py:396 hamster[telnet-92.32.84.20:63784] 
Sat-12-27 08:43PM ERROR  session.py:396 hamster[telnet-92.32.84.20:63784]   File "/home/bld/venv/local/lib/python2.7/site-packages/blessed/terminal.py", line 708, in inkey
Sat-12-27 08:43PM ERROR  session.py:396 hamster[telnet-92.32.84.20:63784]     while not ks and self.kbhit(_timeleft(stime, timeout), _intr_continue):
Sat-12-27 08:43PM ERROR  session.py:396 hamster[telnet-92.32.84.20:63784] 
Sat-12-27 08:43PM ERROR  session.py:396 hamster[telnet-92.32.84.20:63784]   File "x84/terminal.py", line 49, in kbhit
Sat-12-27 08:43PM ERROR  session.py:396 hamster[telnet-92.32.84.20:63784]     val = self.session.read_event('input', timeout)
Sat-12-27 08:43PM ERROR  session.py:396 hamster[telnet-92.32.84.20:63784] 
Sat-12-27 08:43PM ERROR  session.py:396 hamster[telnet-92.32.84.20:63784]   File "x84/bbs/session.py", line 588, in read_event
Sat-12-27 08:43PM ERROR  session.py:396 hamster[telnet-92.32.84.20:63784]     return self.read_events(events=(event,), timeout=timeout)[1]
Sat-12-27 08:43PM ERROR  session.py:396 hamster[telnet-92.32.84.20:63784] 
Sat-12-27 08:43PM ERROR  session.py:396 hamster[telnet-92.32.84.20:63784]   File "x84/bbs/session.py", line 613, in read_events
Sat-12-27 08:43PM ERROR  session.py:396 hamster[telnet-92.32.84.20:63784]     retval = self.buffer_event(event, data)
Sat-12-27 08:43PM ERROR  session.py:396 hamster[telnet-92.32.84.20:63784] 
Sat-12-27 08:43PM ERROR  session.py:396 hamster[telnet-92.32.84.20:63784]   File "x84/bbs/session.py", line 501, in buffer_event
Sat-12-27 08:43PM ERROR  session.py:396 hamster[telnet-92.32.84.20:63784]     chat_script = Script(name='chat', args=(channel, sender,))
Sat-12-27 08:43PM ERROR  session.py:396 hamster[telnet-92.32.84.20:63784] 
Sat-12-27 08:43PM ERROR  session.py:396 hamster[telnet-92.32.84.20:63784] TypeError: __new__() takes exactly 4 arguments (3 given)
Sat-12-27 08:43PM ERROR  session.py:351 hamster[telnet-92.32.84.20:63784] stop after general exception in main
```

**Comment by ericolito** [comment]
fixed.

**Comment by jquast** [comment]
still failing for me, looking

  File "x84/bbs/session.py", line 658, in runscript
    value = module.main(*script.args, **script.kwargs)

  File "/usr/local/src/x84/x84/default/chat.py", line 336, in main
    pager = get_pager(pager)

  File "/usr/local/src/x84/x84/default/chat.py", line 190, in get_pager
    content[row] = ucs

TypeError: 'unicode' object does not support item assignment

**Comment by jquast** [comment]
rewritten, maybe some minor bugs/features remaining
